// <auto-generated />
namespace CinemaTickets.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class MovieFields : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MovieFields));
        
        string IMigrationMetadata.Id
        {
            get { return "202002121644135_MovieFields"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
